# Generated by Django 5.0.6 on 2024-07-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='sub_title',
            field=models.TextField(max_length=500),
        ),
    ]
